apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::991598679485:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1EN7KZTNUQ403
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::991598679485:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-10T13:53:14Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1199"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 80971511-7979-4cec-a30c-990c8c3bd4e7
