apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::991598679485:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-CE7PWS2ING4I
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-07T13:37:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1267"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: d2841dc7-0165-4fec-bd48-e37952bb035a
